image: python:alpine3.14

stages:
    - test
    - deploy

before_script:
    - pip install -r requeriments.txt

CreateReportTests:
    stage: test
    script:
        - python -m pytest --junitxml=report.xml
    artifacts:
        when: always
        reports:
            junit: report.xml

PublishPackage:
    stage: deploy
    script:
        - echo "Successfully Published Package "
        #- poetry build
        #- poetry publish