image: lunesplatform/lunespy

stages:
    - test

CreateTestsReport:
    stage: test
    script:
        - pytest --workers auto --tests-per-worker auto --junitxml=report.xml
    artifacts:
        when: always
        reports:
            junit: report.xml

CreateCoverageReport:
    stage: test
    script:
        - coverage run -m pytest
        - coverage report
        - coverage xml
    artifacts:
        when: always
        reports:
            junit: coverage.xml

DeployGithub:
    stage: deploy
    script:
        - git remote add github https://github.com/lunesplatform/lunespy
        - git push github main
    only:
        - main