image: lunesplatform/lunespy

stages:
    - test


CreateReportTests:
    stage: test
    script:
        - pytest --workers auto --tests-per-worker auto --junitxml=report.xml
    artifacts:
        when: always
        reports:
            junit: report.xml

# CreateReportTestsCoverage:
#     stage: test
#     script:
#         - pytest --workers auto --tests-per-worker auto --cov-report xml:report_cov.xml --cov=lunespy/
#     artifacts:
#         when: always
#         reports:
#             junit: report_cov.xml
