image: registry.lunes.io/blockchain/production/lunespy:latest

stages:
    - test
    - deploy

before_script:
    - pip install -r requeriments.txt

CreateReportTests:
    stage: test
    only:
        refs:
            - main
    script:
        - python3 -m pytest -vv --junitxml=report.xml
    artifacts:
        when: always
        reports:
            junit: report.xml
    after_script:
        - py3clean .

PublishPackage:
    only:
        refs:
            - main
    stage: deploy
    script:
        - echo "Successfully Published Package "
        - git remote add github https://github.com/lunes-platform/lunespy
        - git push main github
        - poetry build
        - poetry publish -u $PYPIUSR -p $PYPIPWD
