image: registry.lunes.io/blockchain/production/lunespy

stages:
    - test

CreateReportTests:
    stage: test
    script:
        - echo $PYTHONPATH
        - pytest -vv --junitxml=report.xml
    artifacts:
        when: always
        reports:
            junit: report.xml
