image: registry.lunes.io/blockchain/production/lunespy

stages:
    - test

CreateReportTests:
    stage: test
    script:
        - pytest -m "not request" --junitxml=report.xml
        - pytest -m request --junitxml=report.xml
    artifacts:
        when: always
        reports:
            junit: report.xml
