image: registry.lunes.io/blockchain/production/lunespy:latest

stages:
    - deploy

CreateReportTests:
    stage: deploy
    only:
        refs:
            - main
    script:
        - python3 -m pytest -vv --junitxml=report.xml
    artifacts:
        when: always
        reports:
            junit: report.xml
    after_script:
        - py3clean .