image: registry.lunes.io/blockchain/production/lunespy:latest

stages:
    - test

CreateReportTests:
    stage: test
    script:
        - python3 -m pytest -vv --junitxml=report.xml
    artifacts:
        when: always
        reports:
            junit: report.xml
