#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# Support module generated by PAGE version 6.2
#  in conjunction with Tcl version 8.6
#    Sep 23, 2021 10:37:44 PM -03  platform: Linux

import sys
import tkinter as tk


def set_Tk_var():
    global nonce
    nonce = tk.StringVar()
    global wallet
    wallet = tk.StringVar()
    wallet.set('wallet')
    global network
    network = tk.IntVar()

def init(top, gui, *args, **kwargs):
    global w, top_level, root
    w = gui
    top_level = top
    root = top

def destroy_window():
    # Function which closes the window.
    global top_level
    top_level.destroy()
    top_level = None

if __name__ == '__main__':
    import lunesdev
    lunesdev.vp_start_gui()

# self.generate.configure(command=lambda: lunesdev_support.generate_wallet(self))




