name: Test

on:
  push:
    branches-ignore: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: python3 -m pip install --upgrade pip -r requirements.txt

    - name: Test with pytest
      run: pytest --workers auto
